### ISSUE TITLE
Cube URI currently not reachable

### ISSUE THREAD

**Issue by IsabelMeraner** [zazuko/rdf-cube-schema#2]
@ktk 
The URI for the `cube:` prefix is currently not reachable:

http://ns.bergnet.org/cube/

Could you please check this?

I was also wondering why the original namespace for the W3C RDF Data Cube Vocabulary (http://purl.org/linked-data/cube#) has not been included in the list of prefixes in the example file cube.ttl.

Thank you so much for your help.

**Comment by ktk** [comment]
@IsabelMeraner correct, while we defined it we did not formalize it. We work on it, will update here!

**Comment by bergos** [comment]
@IsabelMeraner I just created the most basic version of the vocab and published it. [Trifid](https://github.com/zazuko/trifid) is used for content negotiation. I also created a PR to add the vocab to this repo. Once merged, I will change the Trifid config to fetch the vocab file from this repo to have everything in one place.

**Comment by IsabelMeraner** [comment]
Perfect, thanks for the quick feedback and for adding the PR. 

Did you already agree on a time frame when the vocabulary will be available in this repo? Alternatively, do you have a formalized overview or documentation of the vocab that we could have a look at in the meantime?

**Comment by ktk** [comment]
@IsabelMeraner there is a merge-request here https://github.com/zazuko/rdf-cube-schema/pull/3.

**Comment by bergos** [comment]
I changed the [Trifid config](https://github.com/bergos/ns.bergnet.org/blob/master/config.json#L18) to fetch the vocab from this repo to stay synced.
