### ISSUE TITLE
Reuse instance of Measure as MeasureDimension?

### ISSUE THREAD

**Issue by lapidus** [zazuko/rdf-cube-schema#22]
I am trying to wrap my head around MeasureDimensions ...

In our ontology we already have these defined as measures:

```
:population a :Measure
:income_per_person a :Measure
```

Can I simply reuse these instance concepts as properties or do they need to be "disjoint" from those properties?

Compare:

```
:obsX a :Observation;
  :population 999

... versus establishing properties:
:obsX a :Observation;
  :has_population 999
```

It seems handy to avoid the extra level of indirection here, but are there unwanted side-effects of this? 😅 

Thank you!

**Comment by ktk** [comment]
I don't think I understand your question. Is your `:Measure` a `cube:MeasureDimension`? If so, what is the question in the second part in "compare"?

**Comment by lapidus** [comment]
Thx, let me add a bit more detail:

In our knowledge graph we have a class "Measure" where we have instances of measures such as "population" etc.

We have already decorated these with metadata similar to here: 
https://github.com/zazuko/rdf-cube-schema-viz

```
population a :Measure;
   :unit :number .
```

At this point it is intriguing to **also** make population a Property so that we could simply reuse the same concept and its metadata: 

```
population a :Property;

x1 a :Observation;
  :country :sweden;
  :population 999 .
```

I understand this might deviate much from the prescribed way, but trying to find a way to adopt at least parts of the Cube model without redoing our complete ontology ... Is this a terrible idea? ;)

**Comment by ktk** [comment]
In my opinion in your example `population` already _is_ a property so not sure if I miss something here. Maybe this is easier solved if you show me in a call what you mean. You can define `population` as a measure and use it as a property, that's pretty much the point.

**Comment by l00mi** [comment]
Should be clearer now with the combined documentation.
