### ISSUE TITLE
cube validation: shape is required for visualize

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/rdf-cube-schema#24]
https://github.com/zazuko/rdf-cube-schema/blob/41f11b32dbe4d5227158d315535adc96b9d8f501/validation/cube-shape.ttl#L25
@herrstucki AFAIK visualize requires cubes to have a shape, i.e. for filters etc., right?

**Comment by herrstucki** [comment]
@Rdataflow yes but as discussed today what’s in the shape can have different semantics (all possible values vs all values present in the cube).

**Comment by l00mi** [comment]
@Rdataflow what is the goal of this issue?

**Comment by Rdataflow** [comment]
@herrstucki thanks for your input confirming visualize requires at least the present values in the shape.
@l00mi where does zazuko plan to add/extend the validation (GL*195) of the cube incl. its shape? here or elsewhere?

**Comment by l00mi** [comment]
As GL*195 is done before and sets the base lets keep it on GL*275 where you have already proposed. If this is okay for you can you please close this ticket?
