### ISSUE TITLE
Move to respec

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-cube-schema#26]
- [x] Integrate rdf-cube-schema-viz into this repo
- [x] Integrate SHACL Shapes into this repo
- [x] Move to a version in https://respec.org/docs/

**Comment by l00mi** [comment]
also check https://github.com/zazuko/cube-creator/wiki/Context

**Comment by l00mi** [comment]
@bergos I do not remember, are we now okay with moving remaining issues from https://github.com/zazuko/rdf-cube-schema-viz/issues to here?

**Comment by semanticfire** [comment]
> also check https://github.com/zazuko/cube-creator/wiki/Context
This looks more like a specific document for the Swiss context?

**Comment by l00mi** [comment]
No this is for the cube-creator, so it is all defining the overall usage of cubes. Everything swiss related is contained here: https://github.com/zazuko/cube-creator/wiki/LINDAS-Specifics

**Comment by semanticfire** [comment]
I see, what content should be in the cube-schema documentation?

**Comment by l00mi** [comment]
It was only about that the " why, how, what " parts can inform the Introduction, Abstract.

**Comment by semanticfire** [comment]
The current respec document is fully dynamic, so it loads and does the formatting on loading.
Respec has the ability to generate a static document as well, where are the formatting is done once.
I would like to propose to setup a publish pipeline when we PR to master where the static document is loaded a cube.link
The documentation branch would then be the one feeding the github.io version which is still dynamic.

**Comment by l00mi** [comment]
I am okay with that, at the same point in time we should reflect if this repo also creates directly the docker image which does serve https://cube.link.

The spec should become the main page of the trifid on https://cube.link

**Comment by l00mi** [comment]
Will be fixed with #27
