### ISSUE TITLE
Text and samples do not align

### ISSUE THREAD

**Issue by semanticfire** [zazuko/rdf-cube-schema#28]
The samples have observations in observationsets in cubes, this text says otherwise

https://github.com/zazuko/rdf-cube-schema/blob/c7342e0aac7cff1bb218a136638c9d2fd403f1e4/documentation/core.md?plain=1#L40

**Comment by l00mi** [comment]
I think the message here is that all observations need the same structure. Not about how they are connected, I would keep it to that. 

Also remove: "[Cube](#Cube) and [Observation](#Observation) are pretty much self-describing." as i don't see what it wants to say right now.

**Comment by semanticfire** [comment]
The linkage is Cube -- 1-n --> Observationsets -- 1-n --> Observations

where Observation -- 1-n --> Observationsets

There is no direct relation between Cubes and Observations
