### ISSUE TITLE
Purpose of Key and Measure dimension

### ISSUE THREAD

**Issue by semanticfire** [zazuko/rdf-cube-schema#29]
The current collection of documents places the key and measure dimensions in standard constraints.
From the samples, however, it feels more at home in the visualization section.
For now I have moved it there, also @ktk had some remarks wether this is needed at all

**Comment by l00mi** [comment]
The purpose of the KeyDimension is necessary to interpret the cube to understand which dimensions minimally need to be provided to select one observation. A visualization front-end needs to know which filters need to be set to have one observation or a slice. 

The MeasurementDimension does hint the visualization front-end which dimensions have observed values. In contrast to Identifiers or similar.

Finally, by not setting either of these Types, a visualization front-end can decide to use the dimension as additional filter (non mandatory), or simply as information to show.

**Comment by semanticfire** [comment]
This is helpful, from your answer I extract that the Key and Measure dimensions are intended to support visualization tools.
They play no role in constraints that determine if a Cube and its Observations are valid from a structure point of view.

The move from Constraints to Visualization is correct then

**Comment by semanticfire** [comment]
Although we don't like the the title of the chapter ( see #40 ) the dimension description is in the correct location now.
