### ISSUE TITLE
Provide minimal RDFS connections between the core Classes

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-cube-schema#30]
To have a way to easily read the structure of the core classes provide domain and range inside https://github.com/zazuko/rdf-cube-schema/blob/master/vocab.ttl

**Comment by semanticfire** [comment]
I've removed myself from the assignee list, this is a fundamental discussion, which is not solved by 'just add it' and needs input from the creators.

**Comment by l00mi** [comment]
Like which links to add or if links to add?

**Comment by l00mi** [comment]
@ktk @bergos can we go ahead and add the minimal internal domain and range for the core cube?

**Comment by ktk** [comment]
Conclusion:
* domain for the properties we define
* range where absolutely necessary and only on internal projects

**Comment by l00mi** [comment]
- [ ] split in meta.ttl 
- [ ] domain / range

**Comment by semanticfire** [comment]
This is now online
