### ISSUE TITLE
Cube attribute: published/draft -> versioned cubes

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-schema#34]
Cube-level metadata attribute to describe if a cube is "published" or "draft"/"preview"

- So users of visualize.admin.ch **won't** see work-in-progress data.
- So the data owner **will** see work-in-progress data (e.g. on a different domain), so they can try it out.

**Comment by l00mi** [comment]
The general functionality is described at https://zazuko.github.io/rdf-cube-schema/#version-history-of-cubes

The LINDAS / visualize.admin.ch specific information can be found here https://github.com/zazuko/cube-creator/wiki/LINDAS-Specifics#needed-attributes-that-a-cube-shows-up-on-visualizeadminch.

And finally for now we have a remark on the allowed changes for compatibility of the same version line here https://github.com/zazuko/cube-creator/wiki/4.-Publication#to-check-before-a-publication.
