### ISSUE TITLE
Dimension default label path

### ISSUE THREAD

**Issue by bergos** [zazuko/rdf-cube-schema#36]
A property should be defined that can be used to point to a default label. The value should be given as [SHACL property path](https://www.w3.org/TR/shacl/#property-paths).

**Comment by l00mi** [comment]
@bergos is it okay to close this one which is specific for the dimension label, and we keep the discussion on the observation label here https://github.com/zazuko/rdf-cube-schema/issues/42 ?

**Comment by l00mi** [comment]
Closing for now in regards of the Dimension Label. Discussion on the observation label over at #42.
