### ISSUE TITLE
Order in Dimensions

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-cube-schema#37]
from @davidhanimann
> Die Reihenfolge, in der die Tabellenspalten dann angezeigt werden ist komplett anwendungsabhängig? Oder exisitiert eine Möglichkeit, dies zu definieren?

**Comment by semanticfire** [comment]
This is now documented here: https://github.com/zazuko/rdf-cube-schema/blob/7aae60df340bf7adba700c8d5b261cf176051640/documentation/visualization.md?plain=1#L133
