### ISSUE TITLE
Terminology: use Constraints instead of Shapes

### ISSUE THREAD

**Issue by semanticfire** [zazuko/rdf-cube-schema#39]
In the documentation, I've put quite a bit of effort into using `Constraint` instead of `Shapes` , although constraints are shapes I think it is important to focus on a single term.
I'd like to propose to change the shape.ttl to constraint.ttl and make sure our samples use constraint in the URI's instead of shape

**Comment by l00mi** [comment]
Full support.

**Comment by semanticfire** [comment]
fixed in #41
