### ISSUE TITLE
Switch the namespace to "https://cube.link"

### ISSUE THREAD

**Issue by l00mi** [zazuko/rdf-cube-schema#4]
- [x]  https://github.com/zazuko/rdf-cube-view-query/issues/14
- [x]  Deploy trifid on cube.link (see https://github.com/bergos/ns.bergnet.org)
- [x]  Switch Current Data

**Comment by l00mi** [comment]
for the 1.0 switch to `https://cube.link/`

**Comment by ktk** [comment]
@roberthenschel what is the status of deploying the schema at cube.link?

**Comment by bergos** [comment]
Deployment is done. The view lacks a vocab.ttl, but that's something we track in the view repo.

**Comment by l00mi** [comment]
@bergos one tiny detail. should we add a triple pointing to the repo with the specification? So that it can be discovered by looking at cube.link?
