### ISSUE TITLE
Document Meta properties

### ISSUE THREAD

**Issue by semanticfire** [zazuko/rdf-cube-schema#45]
Currently there are some, but not all meta: http//cube.link/meta properties in the main document.
Yesterday on the call we agreed to publish a separate meta document just documenting the meta vocabulary.

This can be a simple separate respec document from the meta subdirectory

**Comment by l00mi** [comment]
We decided on the controlled vocabulary not in general the meta vocabulary. We had already the problem that this practical part of the spec was to hidden and stirred confusion. 

I agree though that if it goes in the direction of lists e.g. controlled vocabularies it should go into a separate document.

**Comment by l00mi** [comment]
Move relation.ttl in `relation` folder. Link from HTML.
