### ISSUE TITLE
shacl: or sh: ? - unify prefix

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/rdf-cube-schema#55]
@l00mi 
currently **shacl:** occurs 3 times in the spec.
is it a misspelling or would it need to be defined?

**Comment by l00mi** [comment]
Sorry, context?

**Comment by l00mi** [comment]
did you see https://zazuko.github.io/rdf-cube-schema/#external

**Comment by Rdataflow** [comment]
sure, here the context...
![image](https://user-images.githubusercontent.com/26090254/154088007-a1bfe1f6-03e7-46ed-88f7-4a0cf74c6bb4.png)
question is, is confusion between?
- shacl
- sh
