### ISSUE TITLE
interlink schema and vocab

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/rdf-cube-schema#60]
interlink schema and {meta,relation} vocab via a href links
* https://zazuko.github.io/rdf-cube-schema/relation/
* https://zazuko.github.io/rdf-cube-schema/meta/
* https://zazuko.github.io/rdf-cube-schema/

for human navigation inbetween them

**Comment by FabianCretton** [comment]
Clarification: why is there no link to /meta and /relation from the main page https://zazuko.github.io/rdf-cube-schema/  ?
