### ISSUE TITLE
inconsistency around relation Classes/Properties

### ISSUE THREAD

**Issue by Rdataflow** [zazuko/rdf-cube-schema#63]
https://zazuko.github.io/rdf-cube-schema/#relexample uses
- `meta:dimensionRelation`
- `meta:relatesTo`

while https://zazuko.github.io/rdf-cube-schema/meta/ defines
- `meta:DimensionRelation` 
- `meta:Relation`
- `meta:relation`

therefore it seems like it would be needed to add to https://zazuko.github.io/rdf-cube-schema/meta/ 
- `meta:dimensionRelation`
- `meta:relatesTo`

and maybe drop those two?
- `meta:Relation`
- `meta:relation`

**Comment by semanticfire** [comment]
@l00mi I've documented the ttl file that came with the examples, but there clearly is an inconsistency in the examples and the vocabulary, how is this currently implemented so that I can fix either the documentation or the vocabulary?

**Comment by l00mi** [comment]
Final:
* meta:dimensionRelation
* meta:relatesTo
* meta:Relation
