### ISSUE TITLE
Fix meta-prefix

### ISSUE THREAD

**Issue by ktk** [zazuko/rdf-cube-schema#68]
It looks we have:

`@prefix: <https://cube.link/meta/>`

for `meta:something` definitions. That looks wrong

**Comment by semanticfire** [comment]
Why is this wrong ?

**Comment by ktk** [comment]
It should be `@prefix meta: <https://cube.link/meta>.`?

**Comment by semanticfire** [comment]
but then meta:blah results in https://cube.link/metablah ?

**Comment by ktk** [comment]
ok sorry the `/` was missing. My point is the `meta` after `@meta` is missing.

**Comment by semanticfire** [comment]
Got it, we were looking at different places!
