### ISSUE TITLE
"sh:minInclusive needs to be an integer" not according to W3C

### ISSUE THREAD

**Issue by sam-e-ch** [zazuko/rdf-cube-schema#86]
At [validation/standalone-constraint-constraint.ttl#L50](https://github.com/zazuko/rdf-cube-schema/blob/main/validation/standalone-constraint-constraint.ttl#L50) there is a validation that `sh:minInclusive` should have datatype integer.

According to [W3C](https://www.w3.org/TR/shacl/#MinInclusiveConstraintComponent ):

> The values of sh:minInclusive in a shape are [literals](https://www.w3.org/TR/shacl/#dfn-literal).

There seems to be a mismatch. E.g. when an observation has datatype `xsd:Date` I would expect the minInclusive to also have the datatype `xsd:Date`.

The same is also true for `sh:maxInclusive`.

cc @Rdataflow

**Comment by sam-e-ch** [comment]
Some additional info:

The cube-creator generates cubes which violate this check, e.g. validating the cube found at https://s.zazuko.com/cpN7Gc returns the following output:

```
cube validation failed
Violation of NodeConstraintComponent: "The constraints do not validate" with path <http://www.w3.org/ns/shacl#property> at focus node <https://environment.ld.admin.ch/foen/aussenhandel-holz-test-3/6/shape/> (source: _:b2)
Violation of DatatypeConstraintComponent: "sh:minInclusive needs to be an integer" with path <http://www.w3.org/ns/shacl#minInclusive> at focus node _:b0_genid-9b739299538f42b383d6af46a2775b20-E2FBA7D1AEC00C6272FBDD4C76C67CB5 (source: _:b11)
Violation of DatatypeConstraintComponent: "sh:maxInclusive needs to be an integer" with path <http://www.w3.org/ns/shacl#maxInclusive> at focus node _:b0_genid-9b739299538f42b383d6af46a2775b20-E2FBA7D1AEC00C6272FBDD4C76C67CB5 (source: _:b13)

```

Maybe this check could even be dropped.

**Comment by tpluscode** [comment]
[sh:minInclusive](https://prefix.zazuko.com/sh:minInclusive) nor other range constraints have a range.

The spec only requires them to be literals and "nodes that are comparable via operators such as <, <=, > and >=" https://www.w3.org/TR/shacl/#core-components-range.

**Comment by semanticfire** [comment]
I think it makes sense to remove the check, or to include a node type constraint for sh:Literal and remove the datatype constraint

**Comment by semanticfire** [comment]
Changed to `sh:nodeType sh:Literal`
